spring:
  profiles:
    active: mlab
server:
  port: 8080
---
spring:
  profiles: dev
  data:
    mongodb:
      database: programador
      host: localhost
      port: 27017
      username:
      password:
---
spring:
  profiles: prod
  data:
    mongodb:
      uri: mongodb+srv://admin2:khrYRcghv4J2uoEt@cluster0-6nd2m.mongodb.net/programador?retryWrites=true&w=majority
      database: programador

---
spring:
  profiles: mlab
  data:
    mongodb:
      uri: mongodb://heroku_vwj36d6r:heroku_vwj36d6r@L8pE@ds033629.mlab.com:33629/heroku_vwj36d6r
      database: programador