spring:
  profiles:
    active: dev
server:
  port: 8085
---
spring:
  profiles: dev
  data:
    mongodb:
      database: programador
      host: localhost
      port: 27017
      username:
      password:
---
spring:
  profiles: prod
  data:
    mongodb:
      uri: mongodb+srv://admin2:khrYRcghv4J2uoEt@cluster0-6nd2m.mongodb.net/programador?retryWrites=true&w=majority
      database: programador