FROM openjdk:11
ADD target/workshop-reactive-programming.jar workshop-reactive-programming.jar
EXPOSE 8085
ENTRYPOINT ["java", "-jar", "workshop-reactive-programming.jar"]
#ENdockeTRYPOINT ["docker", "run", "-p", "8085:8080", "workshop-reactive-programming"]
